version: '3'

services:
  postgres_master:
    container_name: postgres_master
    image: postgres:14.5
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data-slave:/var/lib/postgresql/data-slave
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-script:/etc/postgresql/init-script
      - ./files:/files
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres_slave:
    container_name: postgres_slave
    image: postgres:14.5
    restart: always
    volumes:
      - ./data-slave:/var/lib/postgresql/data
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#   init_service:
#     image: alpine:latest
#     volumes:
#       - ./data:/data
#       - ./docker-init.sh:/init.sh
#     depends_on:
#       - postgres_master
#       - postgres_slave
#     entrypoint: ["/bin/sh", "/docker-init.sh"]

#   data_loader:
#     container_name: data_loader
#     image: python:3.9
#     volumes:
#       - ./data:/data
#       - ./generate_and_import.py:/generate_and_import.py
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     depends_on:
#       - postgres_master
#     entrypoint: ["python", "/generate_and_import.py"]
#   init_load:
#     image: postgres:14.5
#     volumes:
#       - ./files:/data/csv_data
#       - ./docker-init.sh:/docker-init.sh  # Подключаем скрипт загрузки
#     depends_on:
#       - postgres_master
#     entrypoint: ["/bin/bash", "/docker-init.sh"]
#   init_service:
#     image: alpine:latest
#     volumes:
#       - ./data:/data
#       - ./docker-init.sh:/docker-init.sh
#     depends_on:
#       - postgres_master
#       - postgres_slave
#     entrypoint: ["/bin/sh", "/docker-init.sh"]
